[build]
builder = "NIXPACKS"
buildCommand = "cd cms && npm install"

[deploy]
startCommand = "cd cms && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
