[build]
builder = "NIXPACKS"
watchPatterns = ["cms/**"]

[deploy]
startCommand = "cd cms && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
buildCommand = "cd cms && npm ci --only=production"
